name: 'Docker Build and Push'
description: 'Logs into Docker, builds an image, and pushes it to a Docker registry.'

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password or token'
    required: true
    secret: true
  image_name:
    description: 'The Docker image name to build and push'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: './Dockerfile'
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  tags:
    description: 'Comma-separated list of tags for the Docker image'
    required: false
    default: 'latest'

runs:
  using: 'node12'
  main: 'index.js'
