name: 'Docker Build and Push Action (Bash)'

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password or token'
    required: true
    secret: true
  image_name:
    description: 'The Docker image name to build and push'
    required: true
  tags:
    description: 'Comma-separated tags for the Docker image'
    required: false
    default: 'latest'

runs:
  using: 'node12'
  main: 'main.sh'


