name: 'Docker Build and Push Action (Docker)'

description: 'A GitHub Action to build and push Docker images'

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password or token'
    required: true
    secret: true
  image_name:
    description: 'The Docker image name to build and push'
    required: true
  tags:
    description: 'Comma-separated tags for the Docker image'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'munkys123/buildandpushaction:latest'  # The Dockerfile defined in this repository
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.image_name }}
    - ${{ inputs.tags }}

     


